// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus'
import FormController from "./form_controller"
import NotificationController from "./notification_controller"
import ExistsController from "./exists_controller"

const application = Application.start()
application.register("form", FormController)
application.register("notification", NotificationController)
application.register("exists", ExistsController)
